[config.wallpaper]
set = false
command = "swww"
arguments = ["img", "--transition-type", "center"]

[templates.eww]
input_path = "~/.config/matugen/templates/m_colors.scss"
output_path = "~/.config/eww/colors.scss"
export_format = "scss"
# post_hook= 'eww reload'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path  = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/config/colors.conf"

[templates.kitty]
input_path  = "./templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

# [templates.mako]
# input_path = "./templates/mako-config"
# output_path = "~/.config/mako/config"
# post_hook = "killall mako && mako&"

[templates.swayosd]
input_path = "./templates/waybar-colors.css"
output_path = "~/.config/swayosd/colors.css"
post_hook = "killall swayosd-server && swayosd-server&"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path =  './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'



